#!/usr/bin/env python3
"""Generate the bundled `.anim` example animations from fastfetch's builtin ASCII art.

This is a development helper: the generated files in `examples/` are committed and are the
single source of truth (they are also embedded into the moofetch binary at build time).
Run from the repository root:

    python3 tools/gen-animations.py

Effects:
  * shimmer: a highlight band moves down the logo, swapping the art's color placeholders
             (logos without color placeholders get an explicit `$1` base color first)
  * spin:    the logo slowly rotates around its vertical axis (3D spin); horizontal
             compression by cos(angle), characters sampled with nearest neighbour
  * dots:    the three status dots of the generic logo rotate their colors
  * spinner: a hand-written braille spinner

See examples/README.md for the `.anim` file format.
"""

import math
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASCII_DIR = ROOT / "src" / "logo" / "ascii"
OUT_DIR = ROOT / "examples"

HEADER = """\
# {title}
# Generated by tools/gen-animations.py — edit the generator or write your own animation.
# Format documentation: examples/README.md
!fps {fps}
!loop {loop}
{hold}\
"""


def read_art(name: str) -> list[str]:
    art = (ASCII_DIR / name[0].lower() / f"{name}.txt").read_text(encoding="utf-8")
    lines = art.split("\n")
    while lines and lines[-1] == "":
        lines.pop()
    return lines


def has_placeholders(art: list[str]) -> bool:
    return any(re.search(r"\$[0-9]", line) for line in art)


def with_base_color(art: list[str]) -> list[str]:
    """Give logos without color placeholders an explicit `$1` base color.

    Upstream renders such logos in the logo's first color anyway, so this does not change
    the static look; it makes the shimmer effect possible.
    """
    if has_placeholders(art):
        return art
    return [f"$1{line}" for line in art]


def rotate_colors(line: str, mapping: dict[str, str]) -> str:
    # Simultaneous replacement (a naive sequential replace would swap the colors back)
    return re.sub(r"\$[0-9]", lambda match: mapping.get(match.group(0), match.group(0)), line)


def shimmer(art: list[str], frames: int = 8, band: int = 4, colors: int = 2) -> list[list[str]]:
    """A moving band of `band` lines where color placeholders are rotated."""
    art = with_base_color(art)
    if colors == 2:
        mapping = {"$1": "$2", "$2": "$1"}
    else:  # 3-color rotation
        mapping = {"$1": "$2", "$2": "$3", "$3": "$1"}

    height = len(art)
    result = []
    for frame in range(frames):
        center = frame * height // frames
        out = []
        for i, line in enumerate(art):
            distance = (i - center) % height
            out.append(rotate_colors(line, mapping) if distance < band else line)
        result.append(out)
    return result


def parse_grid(art: list[str]) -> list[list[tuple[str, int]]]:
    """Split art into cells of (character, color index). Colors carry forward like upstream."""
    grid = []
    for line in art:
        row = []
        color = 1
        i = 0
        while i < len(line):
            char = line[i]
            if char == "$" and i + 1 < len(line):
                nxt = line[i + 1]
                if nxt.isdigit():
                    color = int(nxt)
                    i += 2
                    continue
                if nxt == "$":
                    row.append(("$", color))
                    i += 2
                    continue
            row.append((char, color))
            i += 1
        grid.append(row)
    return grid


def spin(art: list[str], frames: int = 36, min_scale: float = 0.06) -> list[list[str]]:
    """Slowly rotate the logo around its vertical axis (3D spin).

    The source art is compressed horizontally by cos(angle) and characters are sampled
    with nearest neighbour; when cos(angle) is negative the logo shows its mirrored back
    side, which is what makes the spin read as a rotation. The canvas keeps the original
    width and height, so the animation occupies exactly the same terminal region as the
    static logo.
    """
    grid = parse_grid(art)
    height = len(grid)
    width = max(len(row) for row in grid)
    for row in grid:
        row.extend([(" ", 1)] * (width - len(row)))

    center = (width - 1) / 2
    result = []
    for frame in range(frames):
        angle = 2 * math.pi * frame / frames
        scale = math.cos(angle)
        if abs(scale) < min_scale:
            scale = min_scale if scale >= 0 else -min_scale

        out = []
        for y in range(height):
            cells = []
            last_non_space = -1
            for x in range(width):
                source_x = round(center + (x - center) / scale)
                if 0 <= source_x < width and grid[y][source_x][0] != " ":
                    cells.append(grid[y][source_x])
                    last_non_space = x
                else:
                    cells.append((" ", 1))

            line = []
            current_color = None
            for x in range(last_non_space + 1):
                char, color = cells[x]
                if char == " ":
                    line.append(" ")
                    continue
                if color != current_color:
                    line.append(f"${color}")
                    current_color = color
                line.append("$$" if char == "$" else char)
            out.append("".join(line))
        result.append(out)
    return result


def write_animation(name: str, title: str, frames: list[list[str]], fps: int = 12, loop: int = 2, hold: str | None = None) -> None:
    out = HEADER.format(title=title, fps=fps, loop=loop, hold=f"!hold {hold}\n" if hold else "")
    for frame in frames:
        out += "---\n"
        for line in frame:
            out += line + "\n"
    OUT_DIR.mkdir(exist_ok=True)
    (OUT_DIR / f"{name}.anim").write_text(out, encoding="utf-8")
    print(f"wrote examples/{name}.anim ({len(frames)} frames)")


# Distros rendered with the moving-highlight effect. The file name becomes the built-in
# animation name and is matched (case-insensitively, `-` == `_`) against the detected OS id.
SHIMMER_DISTROS = [
    "arch",
    "cachyos",
    "debian",
    "fedora",
    "ubuntu",
    "opensuse",
    "opensuse_leap",
    "opensuse_tumbleweed",
    "linuxmint",
    "pop",
    "manjaro",
    "endeavouros",
    "garuda",
    "nixos",
    "gentoo",
    "alpine",
    "kali",
    "void",
    "elementary",
    "zorin",
    "mx",
    "deepin",
    "artix",
    "rhel",
    "rocky",
    "almalinux",
    "centos",
    "slackware",
    "raspbian",
    "parrot",
    "devuan",
]


def main() -> None:
    for name in SHIMMER_DISTROS:
        art = read_art(name)
        colors = 3 if name == "cachyos" else 2
        write_animation(name, f"{name} — moving highlight band", shimmer(art, colors=colors))

    # Slowly rotating logos (one 360° revolution, ~4.5 s, then freeze on the original)
    write_animation(
        "arch_rotate",
        "Arch Linux — slow 3D spin around the vertical axis",
        spin(read_art("arch")),
        fps=8, loop=1, hold="first",
    )
    write_animation(
        "cachyos_rotate",
        "CachyOS — slow 3D spin around the vertical axis",
        spin(read_art("cachyos")),
        fps=8, loop=1, hold="first",
    )

    # Generic: rotate the color of the three status dots in the header line
    generic = read_art("fastfetch")
    dot_frames = []
    for frame in range(6):
        out = list(generic)
        dots = ["$2", "$3", "$4"]
        rotated = dots[frame % 3 :] + dots[: frame % 3]
        out[1] = out[1].replace("$2● $3● $4●", f"{rotated[0]}● {rotated[1]}● {rotated[2]}●")
        dot_frames.append(out)
    write_animation("default", "Generic logo — color-rotating status dots", dot_frames, fps=8, loop=3)

    # Spinner: a minimal custom animation
    spinner_chars = "⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏"
    spinner_frames = [
        ["   $1" + char + "  $2moofetch", "       $3animate your logo"]
        for char in spinner_chars
    ]
    write_animation("spinner", "Minimal braille spinner (custom art)", spinner_frames, fps=10, loop=2)


if __name__ == "__main__":
    main()
