#!/usr/bin/env python3
"""Generate the bundled `.anim` example animations from fastfetch's builtin ASCII art.

This is a development helper: the generated files in `examples/` are committed and are the
single source of truth (they are also embedded into the moofetch binary at build time).
Run from the repository root:

    python3 tools/gen-animations.py

Effects:
  * shimmer: a highlight band moves down the logo, swapping the art's color placeholders
  * dots:    the three status dots of the generic logo rotate their colors
  * spinner: a hand-written braille spinner

See examples/README.md for the `.anim` file format.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASCII_DIR = ROOT / "src" / "logo" / "ascii"
OUT_DIR = ROOT / "examples"

HEADER = """\
# {title}
# Generated by tools/gen-animations.py — edit the generator or write your own animation.
# Format documentation: examples/README.md
!fps {fps}
!loop {loop}
"""


def read_art(name: str) -> list[str]:
    art = (ASCII_DIR / name[0].lower() / f"{name}.txt").read_text(encoding="utf-8")
    lines = art.split("\n")
    while lines and lines[-1] == "":
        lines.pop()
    return lines


def rotate_colors(line: str, mapping: dict[str, str]) -> str:
    for old, new in mapping.items():
        line = line.replace(old, new)
    return line


def shimmer(art: list[str], frames: int = 8, band: int = 4, colors: int = 2) -> list[list[str]]:
    """A moving band of `band` lines where color placeholders are rotated."""
    if colors == 2:
        mapping = {"$1": "$2", "$2": "$1"}
    else:  # 3-color rotation
        mapping = {"$1": "$2", "$2": "$3", "$3": "$1"}

    height = len(art)
    result = []
    for frame in range(frames):
        center = frame * height // frames
        out = []
        for i, line in enumerate(art):
            distance = (i - center) % height
            out.append(rotate_colors(line, mapping) if distance < band else line)
        result.append(out)
    return result


def write_animation(name: str, title: str, frames: list[list[str]], fps: int = 12, loop: int = 2) -> None:
    out = HEADER.format(title=title, fps=fps, loop=loop)
    for frame in frames:
        out += "---\n"
        for line in frame:
            out += line + "\n"
    OUT_DIR.mkdir(exist_ok=True)
    (OUT_DIR / f"{name}.anim").write_text(out, encoding="utf-8")
    print(f"wrote examples/{name}.anim ({len(frames)} frames)")


def main() -> None:
    write_animation("arch", "Arch Linux — moving highlight band", shimmer(read_art("arch")))
    write_animation("ubuntu", "Ubuntu — moving highlight band", shimmer(read_art("ubuntu")))
    write_animation("debian", "Debian — moving highlight band", shimmer(read_art("debian")))
    write_animation("fedora", "Fedora — moving highlight band", shimmer(read_art("fedora")))
    write_animation(
        "cachyos",
        "CachyOS — moving highlight band across three palette colors",
        shimmer(read_art("cachyos"), colors=3),
    )

    # Generic: rotate the color of the three status dots in the header line
    generic = read_art("fastfetch")
    dot_frames = []
    for frame in range(6):
        out = list(generic)
        dots = ["$2", "$3", "$4"]
        rotated = dots[frame % 3 :] + dots[: frame % 3]
        out[1] = out[1].replace("$2● $3● $4●", f"{rotated[0]}● {rotated[1]}● {rotated[2]}●")
        dot_frames.append(out)
    write_animation("default", "Generic logo — color-rotating status dots", dot_frames, fps=8, loop=3)

    # Spinner: a minimal custom animation
    spinner_chars = "⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏"
    spinner_frames = [
        ["   $1" + char + "  $2moofetch", "       $3animate your logo"]
        for char in spinner_chars
    ]
    write_animation("spinner", "Minimal braille spinner (custom art)", spinner_frames, fps=10, loop=2)


if __name__ == "__main__":
    main()
